In [1]:
import pandas as pd
import numpy as np
from catboost import  Pool
from sklearn.model_selection import train_test_split
from sklearn.utils.class_weight import compute_class_weight
from catboost import CatBoostClassifier
from sklearn.metrics import f1_score

In [2]:
dfff = pd.read_csv('train_data.csv')

In [3]:
y_test_object = dfff['object']
y_test_relevant = dfff['is_relevant']
y_test_positive = dfff['is_positive']

In [4]:
df_embed_object_test = pd.read_csv('testing_loader_is_obj.csv')
df_embed_object_test = df_embed_object_test.drop(['Unnamed: 0'], axis=1)

df_embed_is_relevant_test = pd.read_csv('testing_loader_is_relevant.csv')
df_embed_is_relevant_test = df_embed_is_relevant_test.drop(['Unnamed: 0'], axis=1)

df_embed_is_positive_test = pd.read_csv('testing_loader_is_positive.csv')
df_embed_is_positive_test = df_embed_is_positive_test.drop(['Unnamed: 0'], axis=1)

In [5]:
df_embed_object = pd.read_csv('training_loader_is_obj.csv')
df_embed_object = df_embed_object.drop(['Unnamed: 0'], axis=1)

df_embed_is_relevant = pd.read_csv('training_loader_is_obj.csv')
df_embed_is_relevant = df_embed_is_relevant.drop(['Unnamed: 0'], axis=1)

df_embed_is_positive = pd.read_csv('training_loader_is_obj.csv')
df_embed_is_positive = df_embed_is_positive.drop(['Unnamed: 0'], axis=1)

In [6]:
data = pd.read_csv("itog_data.csv")
objectt = data['object']

data = pd.read_csv("itog_data.csv")
relevant = data['is_relevant']

data = pd.read_csv("itog_data.csv")
positive = data['is_positive']

In [10]:
from sklearn.utils import compute_class_weight

# object

In [11]:
class_weights_ob = compute_class_weight(class_weight = 'balanced', classes = np.unique(objectt),y = objectt)

In [13]:
class_weights_ob

array([1.05115907, 1.01701469, 0.93861527])

In [87]:
model_objectt = CatBoostClassifier(iterations=3000,
                                    learning_rate=0.01,
                                    depth=2,
                                    eval_metric='MultiClass',
                                    random_seed=0,
                                    class_weights= class_weights_ob
                                    # early_stopping_rounds=50
                                    )

In [88]:
train_pool_ob = Pool(df_embed_object, objectt)
val_pool_ob = Pool(df_embed_object_test, y_test_object)


model_objectt.fit(train_pool_ob, eval_set= val_pool_ob, plot=True)

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

0:	learn: 1.0972070	test: 1.0974747	best: 1.0974747 (0)	total: 21.7ms	remaining: 1m 5s
1:	learn: 1.0960324	test: 1.0962635	best: 1.0962635 (1)	total: 42.4ms	remaining: 1m 3s
2:	learn: 1.0949031	test: 1.0956448	best: 1.0956448 (2)	total: 56ms	remaining: 56s
3:	learn: 1.0934120	test: 1.0937703	best: 1.0937703 (3)	total: 67.3ms	remaining: 50.4s
4:	learn: 1.0919116	test: 1.0922334	best: 1.0922334 (4)	total: 75.4ms	remaining: 45.2s
5:	learn: 1.0904739	test: 1.0915648	best: 1.0915648 (5)	total: 84.8ms	remaining: 42.3s
6:	learn: 1.0890005	test: 1.0899528	best: 1.0899528 (6)	total: 92.7ms	remaining: 39.6s
7:	learn: 1.0874709	test: 1.0892528	best: 1.0892528 (7)	total: 101ms	remaining: 37.7s
8:	learn: 1.0855132	test: 1.0877795	best: 1.0877795 (8)	total: 108ms	remaining: 35.9s
9:	learn: 1.0841265	test: 1.0871185	best: 1.0871185 (9)	total: 116ms	remaining: 34.7s
10:	learn: 1.0823918	test: 1.0858953	best: 1.0858953 (10)	total: 123ms	remaining: 33.5s
11:	learn: 1.0810870	test: 1.0850358	best: 1.0850

In [89]:
val_preds_оb = model_objectt.predict(df_embed_object_test)

In [90]:
from sklearn.metrics import f1_score
f1_val_ob = f1_score(y_test_object, np.array(val_preds_оb).ravel(), average='micro')  
# Или можно использовать 'macro' или 'weighted' в зависимости от вашего выбора
print("F1 Score:", f1_val_ob)

F1 Score: 0.7475728155339806


# relevant

In [95]:
class_weights_rel = compute_class_weight(class_weight = 'balanced', classes = np.unique(relevant),y = relevant)


In [113]:
model_relevant = CatBoostClassifier(iterations=500,
                                    learning_rate=0.00001,
                                    # loss_function = 'Logloss',
                                    depth=2,
                                    eval_metric='F1',
                                    random_seed=42,

                                    # class_weights=[3, 1]
                                    class_weights =class_weights_rel
                                    # early_stopping_rounds=50
                                    )


In [114]:
train_pool_rel = Pool(df_embed_is_relevant, relevant)
val_pool_rel= Pool(df_embed_is_relevant_test, y_test_relevant)


model_relevant.fit(train_pool_rel, eval_set=val_pool_rel, plot=True)

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

0:	learn: 0.7794179	test: 0.8857473	best: 0.8857473 (0)	total: 21.8ms	remaining: 10.9s
1:	learn: 0.8165997	test: 0.8857473	best: 0.8857473 (0)	total: 26.8ms	remaining: 6.68s
2:	learn: 0.8479779	test: 0.8802372	best: 0.8857473 (0)	total: 31.8ms	remaining: 5.27s
3:	learn: 0.8495627	test: 0.8802372	best: 0.8857473 (0)	total: 36.9ms	remaining: 4.58s
4:	learn: 0.8479400	test: 0.8857473	best: 0.8857473 (0)	total: 41.9ms	remaining: 4.15s
5:	learn: 0.8625040	test: 0.8857473	best: 0.8857473 (0)	total: 47.6ms	remaining: 3.92s
6:	learn: 0.8600292	test: 0.8857473	best: 0.8857473 (0)	total: 52.4ms	remaining: 3.69s
7:	learn: 0.8564571	test: 0.8857473	best: 0.8857473 (0)	total: 57.9ms	remaining: 3.56s
8:	learn: 0.8508305	test: 0.8857473	best: 0.8857473 (0)	total: 62.6ms	remaining: 3.41s
9:	learn: 0.8598244	test: 0.8857473	best: 0.8857473 (0)	total: 68.2ms	remaining: 3.34s
10:	learn: 0.8589433	test: 0.8857473	best: 0.8857473 (0)	total: 73.2ms	remaining: 3.25s
11:	learn: 0.8656536	test: 0.8857473	best:

In [117]:
val_preds_rel = model_relevant.predict(df_embed_is_relevant_test)

In [118]:
from sklearn.metrics import f1_score
f1_val_rel = f1_score(y_test_relevant, np.array(val_preds_rel).ravel(), average='macro')
print("F1 Score:", f1_val_rel)

F1 Score: 0.5401785714285714


In [106]:
predictions_rel = model_relevant.predict(df_embed_is_relevant_test)
relevant_df_pred = pd.DataFrame({'is_relevant': predictions_rel})

In [103]:
relevant_df_pred

is_relevant
0              1
1              1
2              1
3              1
4              1
..           ...
98             1
99             1
100            1
101            1
102            1

[103 rows x 1 columns]

# positive

In [120]:
class_weights_pos = compute_class_weight(class_weight = 'balanced', classes = np.unique(positive),y = positive)
class_weights_pos

array([1.25957854, 0.82912989])

In [308]:
model_positive = CatBoostClassifier(iterations=50,
                                    learning_rate=0.0001,
                                    depth=4,
                                    eval_metric='F1',
                                    random_seed=42,

                                    class_weights=[3, 5]
                                    #  class_weights =class_weights_pos
                                    # early_stopping_rounds=50
                                    )

In [309]:
train_pool_pos = Pool(df_embed_is_relevant, relevant)
val_pool_pos= Pool(df_embed_is_relevant_test, y_test_relevant)


model_positive.fit(train_pool_pos, eval_set=val_pool_pos, plot=True)

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

0:	learn: 0.8845774	test: 0.9584665	best: 0.9584665 (0)	total: 29.7ms	remaining: 1.45s
1:	learn: 0.8909189	test: 0.8510638	best: 0.9584665 (0)	total: 55.1ms	remaining: 1.32s
2:	learn: 0.9017279	test: 0.9357998	best: 0.9584665 (0)	total: 68.3ms	remaining: 1.07s
3:	learn: 0.9008912	test: 0.9357998	best: 0.9584665 (0)	total: 81ms	remaining: 932ms
4:	learn: 0.8965738	test: 0.9415584	best: 0.9584665 (0)	total: 94.4ms	remaining: 849ms
5:	learn: 0.8986003	test: 0.9528908	best: 0.9584665 (0)	total: 109ms	remaining: 797ms
6:	learn: 0.8969039	test: 0.9584665	best: 0.9584665 (0)	total: 125ms	remaining: 766ms
7:	learn: 0.8988884	test: 0.9584665	best: 0.9584665 (0)	total: 138ms	remaining: 722ms
8:	learn: 0.8951733	test: 0.9584665	best: 0.9584665 (0)	total: 150ms	remaining: 685ms
9:	learn: 0.8980505	test: 0.9584665	best: 0.9584665 (0)	total: 164ms	remaining: 654ms
10:	learn: 0.8946026	test: 0.9584665	best: 0.9584665 (0)	total: 176ms	remaining: 623ms
11:	learn: 0.8977636	test: 0.9584665	best: 0.95846

In [304]:
val_preds_pos = model_positive.predict(df_embed_is_positive_test)

In [305]:
from sklearn.metrics import f1_score
f1_val_pos = f1_score(y_test_positive, np.array(val_preds_pos).ravel(), average='macro')
print("F1 Score:", f1_val_pos)

F1 Score: 0.5283882783882784


In [ ]:

val_preds_pos = best_model.predict(df_embed_is_positive_test)
from sklearn.metrics import f1_score
f1_val_pos = f1_score(y_test_positive, np.array(val_preds_pos).ravel(), average='macro')
print("F1 Score:", f1_val_pos)

СУПЕР ВАЖНАЯ ФУНКЦИЯ 


In [198]:
def evaluate_model(y_true, y_pred):
    precision = precision_score(y_true, y_pred, average='macro')
    recall = recall_score(y_true, y_pred, average='macro')
    f1 = f1_score(y_true, y_pred, average='macro')
    return precision, recall, f1


In [199]:
evaluate_model(y_test_positive, val_preds_pos)

(0.8623417721518987, 0.9138554216867469, 0.8843995510662177)

In [200]:
evaluate_model(y_test_relevant, val_preds_rel)

(0.45173160173160176, 0.4047008547008547, 0.4122282608695652)

In [201]:
evaluate_model(y_test_object, val_preds_оb)

(0.7856118056978888, 0.7733500417710945, 0.7692637305313362)

In [ ]:
predictions_pos = model_positive.predict(X_test_positive)

# Создание датафрейма с одной колонкой "object"
positive_df_pred = pd.DataFrame({'is_relevant': predictions_pos})

In [102]:
np.array(val_preds_pos).ravel()

array([1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1.,
       1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 0., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0.,
       1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1.,
       0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1.,
       1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       1., 0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1.])