In [141]:
import pandas as pd
import numpy as np
from catboost import  Pool

In [37]:
# test = pd.read_csv('train_data.csv')

In [202]:
y_test_object = dfff['object']
y_test_relevant = dfff['is_relevant']
y_test_positive = dfff['is_positive']

In [38]:
df_embed_object_test = pd.read_csv('testing_loader_is_obj.csv')
df_embed_object_test = df_embed_object_test.drop(['Unnamed: 0'], axis=1)

df_embed_is_relevant_test = pd.read_csv('testing_loader_is_relevant.csv')
df_embed_is_relevant_test = df_embed_is_relevant_test.drop(['Unnamed: 0'], axis=1)

df_embed_is_positive_test = pd.read_csv('testing_loader_is_positive.csv')
df_embed_is_positive_test = df_embed_is_positive_test.drop(['Unnamed: 0'], axis=1)

In [39]:
df_embed_object_test

0         1         2         3         4         5         6  \
0    1.819988  1.456836  0.534247 -0.933210  1.053786 -0.523906 -0.423341   
1    1.821165  1.153605  1.294124 -0.503846  1.615947  0.453258  0.756165   
2    1.726662  1.417836  0.303546  0.293890  1.403222 -0.860797  0.111260   
3    1.021890  0.584763  0.562886 -0.214653  1.193114  0.103155  0.271906   
4    1.518000  0.736485  1.734105 -0.625285  1.753641  0.695611  0.067282   
..        ...       ...       ...       ...       ...       ...       ...   
98   0.549174  0.208230  0.897971  0.389525  1.043129 -0.706849  0.331326   
99   1.719570 -0.166071  0.694928 -1.134908  0.054209 -0.372658  0.931460   
100  1.801103  1.336007  0.176347  0.616264  1.615015 -1.054917  0.692730   
101  0.525282  2.437926 -0.060151  0.133630  0.244353 -1.311379  0.488250   
102  0.450983  1.141354 -0.739413 -0.039502 -0.022430 -0.510699 -0.416611   

            7         8         9  ...      1014      1015      1016  \
0    0.179282  0.029044 -1.141256  ...  0.427779 -0.253550  0.059471   
1    0.410842  0.683587 -2.204774  ...  0.081195 -0.536537 -0.231887   
2    0.463520  0.232723 -1.429144  ... -0.490042  0.119783  0.790294   
3    0.327889  0.330823 -0.905167  ... -0.160092  0.082831  0.554160   
4    0.523918  0.532878 -1.778042  ... -0.554764 -0.548313 -0.257401   
..        ...       ...       ...  ...       ...       ...       ...   
98   0.672795  0.215903  0.437685  ... -0.152836  0.946763 -0.417733   
99   0.300263  1.195855 -1.708477  ...  0.122851 -0.075467  0.691573   
100 -0.028688  0.615677 -1.694494  ... -1.073030  0.171361  0.744687   
101 -0.374377  0.327947 -0.954208  ... -1.021292 -0.157478 -1.189214   
102 -0.367690 -0.371282 -0.550658  ... -0.049433  0.002699 -0.221565   

         1017      1018      1019      1020      1021      1022      1023  
0    0.049093  0.507716 -0.223098  1.884622  1.023462 -0.004000  0.929772  
1    0.128094  0.182182  0.088216  0.987913  0.679478 -0.162850  0.550229  
2    0.394863  0.530586  1.355181  0.828390  1.924209 -0.250320  0.244012  
3    1.036684 -0.317098  1.004722  0.765619  1.116626  0.624340  0.743188  
4    1.133345 -0.232489  0.802471 -0.282655  0.801978 -0.040680  0.029833  
..        ...       ...       ...       ...       ...       ...       ...  
98   0.035963 -0.495300  0.876636  1.802597  1.682215 -0.454542 -0.311649  
99   0.756575 -0.713027 -0.034626  0.950518  0.773378  0.588973  0.730353  
100  0.402765 -0.540061 -0.017221  1.452997  1.859108  0.533691  0.661298  
101  0.255465  0.807358  1.275683  1.116052  0.898370  0.576179 -0.010904  
102 -0.173850  0.377770  1.114155  0.556916  0.395185  0.544598 -0.312183  

[103 rows x 1024 columns]

In [40]:
df_embed_object = pd.read_csv('training_loader_is_obj.csv')
df_embed_object = df_embed_object.drop(['Unnamed: 0'], axis=1)

df_embed_is_relevant = pd.read_csv('training_loader_is_obj.csv')
df_embed_is_relevant = df_embed_is_relevant.drop(['Unnamed: 0'], axis=1)

df_embed_is_positive = pd.read_csv('training_loader_is_obj.csv')
df_embed_is_positive = df_embed_is_positive.drop(['Unnamed: 0'], axis=1)

In [41]:
data = pd.read_csv("itog_data.csv")
objectt = data['object']

data = pd.read_csv("itog_data.csv")
relevant = data['is_relevant']

data = pd.read_csv("itog_data.csv")
positive = data['is_positive']

In [42]:
from sklearn.model_selection import train_test_split
from sklearn.utils.class_weight import compute_class_weight
from catboost import CatBoostClassifier
from sklearn.metrics import f1_score

# object

In [44]:
class_weights = compute_class_weight(class_weight = 'balanced', classes = np.unique(objectt),y = objectt)

In [45]:
class_weights

array([1.05115907, 1.01701469, 0.93861527])

In [203]:
model_objectt = CatBoostClassifier(iterations=1000,
                   learning_rate=0.001,
                                    depth=5,
                                    eval_metric='F1',
                                    random_seed=0,
                                    # class_weights=[3, 1]
               )

In [204]:
train_pool = Pool(df_embed_object, objectt)
val_pool = Pool(df_embed_object_test, y_test_object)


model_objectt.fit(train_pool, eval_set=val_pool, plot=True)

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

CatBoostError: /Users/zomb-ml-platform-msk/go-agent-21.2.0/pipelines/BuildMaster/catboost.git/catboost/libs/metrics/metric.cpp:6583: Eval metric should have a single value. Metric F1 provides a value for each class, thus it cannot be used as a single value to select best iteration or to detect overfitting. If you just want to look on the values of this metric use custom_metric parameter.

In [69]:
model_objectt.fit(df_embed_object, objectt, use_best_model=True)

You should provide test set for use best model. use_best_model parameter has been switched to false value.


0:	learn: 1.0793585	total: 88.7ms	remaining: 1m 28s
1:	learn: 1.0613604	total: 127ms	remaining: 1m 3s
2:	learn: 1.0439679	total: 156ms	remaining: 51.8s
3:	learn: 1.0312556	total: 188ms	remaining: 46.9s
4:	learn: 1.0107988	total: 226ms	remaining: 45s
5:	learn: 0.9931833	total: 264ms	remaining: 43.7s
6:	learn: 0.9766561	total: 291ms	remaining: 41.2s
7:	learn: 0.9631851	total: 318ms	remaining: 39.4s
8:	learn: 0.9493693	total: 365ms	remaining: 40.2s
9:	learn: 0.9327867	total: 396ms	remaining: 39.2s
10:	learn: 0.9200615	total: 424ms	remaining: 38.1s
11:	learn: 0.9092855	total: 449ms	remaining: 36.9s
12:	learn: 0.8969268	total: 477ms	remaining: 36.2s
13:	learn: 0.8880391	total: 515ms	remaining: 36.3s
14:	learn: 0.8782722	total: 562ms	remaining: 36.9s
15:	learn: 0.8684156	total: 619ms	remaining: 38.1s
16:	learn: 0.8572522	total: 667ms	remaining: 38.6s
17:	learn: 0.8499593	total: 710ms	remaining: 38.8s
18:	learn: 0.8407306	total: 755ms	remaining: 39s
19:	learn: 0.8311070	total: 799ms	remaining

In [35]:
df_embed_object

0         1         2         3         4         5         6  \
0     0.316807  0.951419  1.125916 -0.583216  1.120975  0.339260  0.808406   
1    -0.087736  0.876837  1.234571  0.502994  1.321145  0.080797  0.754770   
2     0.902405  1.073222  0.239419 -0.373607  0.505982 -0.473654  0.783543   
3     0.587279  1.337170  1.702893 -0.045942  1.229969 -0.155676  0.654452   
4     0.256153  1.126067 -0.095492 -0.003338  0.140351  0.147858  0.351394   
...        ...       ...       ...       ...       ...       ...       ...   
1310  1.614966  1.185175 -0.065633  1.254580  0.975489  0.030621 -0.061445   
1311  1.267671  0.253196  0.816890 -0.404507  1.547385  0.430387  0.187600   
1312  1.458570  1.209718 -0.096702 -0.157865  0.272248 -0.202475 -0.457379   
1313  0.292219  0.217589  0.296535  0.540016  0.000570  0.303169  0.297143   
1314  0.499721  0.521001  0.708110  0.346432  0.716572 -0.595854  0.486432   

             7         8         9  ...      1015      1016      1017  \
0    -0.577238  0.303803 -0.781883  ...  0.321721  0.056304  0.338744   
1    -0.042851  0.044607 -1.087136  ... -0.031850 -0.110181  0.333206   
2     0.028223  1.499530 -0.601483  ...  0.973643  0.051150  1.233385   
3    -0.126383  0.708077 -1.015595  ...  0.398528  0.248788  0.961042   
4     0.364050  0.858072 -0.330021  ... -0.162588  0.169264  0.801297   
...        ...       ...       ...  ...       ...       ...       ...   
1310  0.116094  1.506479 -1.184993  ...  0.692301 -0.404869  0.963184   
1311 -0.098917  0.285840 -1.388438  ... -0.004469 -0.179113  1.113156   
1312  0.142288  0.510280 -0.881846  ...  1.339681  0.488333  0.604162   
1313 -0.110447  0.274678 -1.729382  ...  0.220720 -0.620352  0.829571   
1314 -0.220957  1.002750 -1.788009  ...  0.068947 -0.678630 -0.206480   

          1018      1019      1020      1021      1022      1023  object  
0     0.436469  0.732455  1.827020  0.212860  0.475600  0.984609       0  
1    -0.232041  0.704285  2.766802  1.948597 -0.208141  0.363582       0  
2    -0.266724  1.076756  1.519801  1.594607 -0.220974  0.254262       0  
3    -0.649355  0.991507  1.722945  1.255724 -0.007846  0.990063       0  
4     1.072792  1.716442  1.981877  0.554500  0.374218  0.108822       0  
...        ...       ...       ...       ...       ...       ...     ...  
1310  0.420389  0.828661  0.472502  1.075158  0.441580  0.900833       1  
1311 -1.208977  0.391380  1.917160  1.011393 -0.057966  0.251528       1  
1312  0.655320  0.354929  1.645489  1.051243  1.244690  1.130223       1  
1313 -0.589299 -0.232839 -0.581093  0.539268 -0.140743  0.729236       2  
1314 -0.019640  0.099412  0.596459  0.938596  0.165016  1.029305       2  

[1315 rows x 1025 columns]

In [77]:
dfff = pd.read_csv('train_data.csv')
dfff

timestamp               question_1  \
0    2024-04-01 08:30:00  Основы программирования   
1    2024-04-01 10:00:00  Основы программирования   
2    2024-04-01 15:00:00  Основы программирования   
3    2024-04-01 17:00:00  Основы программирования   
4    2024-04-02 09:00:00  Основы программирования   
..                   ...                      ...   
98   2024-04-24 10:22:00  Основы программирования   
99   2024-04-24 18:00:00  Новейшие тенденции в IT   
100  2024-04-25 20:00:00  Новейшие тенденции в IT   
101     27.04.2024:19:00       Java api браузеров   
102     27.04.2024:19:00       Java api браузеров   

                                            question_2  \
0    Интерактивный подход к изучению основ C# был о...   
1    Подробное объяснение логических операторов в J...   
2    Введение в программирование на Python было про...   
3    Понятное изложение основных понятий, хорошая с...   
4    Кларность и структура материала по основам Jav...   
..                                                 ...   
98   Преподователь раз такой умный , зачем за гроши...   
99   Очень понравилось изучение применения технолог...   
100          Очень подробный разбор сложных концепций.   
101                                   Понравилась тема   
102                    Понравился методический вебинар   

                                            question_3  \
0                                                 Нет.   
1                                                 Нет.   
2                                                 Нет.   
3    Да, циклы for и while были объяснены слишком б...   
4                                                 Нет.   
..                                                 ...   
98                                            Унижение   
99   Да, тема разработки контента для VR была недос...   
100  Сложности с пониманием асинхронного программир...   
101  Да, преподователь нес чушь и путался в своих ж...   
102                          Преподователь сошел с ума   

                                            question_4  \
0    Увеличить количество практических заданий для ...   
1    Предоставить ещё больше практических задач пос...   
2    Улучшить качество видеоматериалов, иногда было...   
3    Добавить видеоматериалы для самостоятельного и...   
4    Ввести больше примеров на работу с массивами и...   
..                                                 ...   
98                       Уважать студентов и не хамить   
99   Организовать практические занятия по созданию ...   
100                    Нужно больше примеров из жизни.   
101                            Поменяйте преподователя   
102  Я думаю с другим преподователем я получил бы б...   

                                            question_5  is_relevant  object  \
0             Введение в разработку на .NET Framework.            1       0   
1    Детальное изучение асинхронного программирован...            1       0   
2    Библиотеки Python для анализа данных и машинно...            1       0   
3                     Функциональное программирование.            1       0   
4             Работа с асинхронным кодом в JavaScript.            1       0   
..                                                 ...          ...     ...   
98                                     К преподователю            1       2   
99   Разработка приложений для виртуальной реальности.            1       2   
100                   Разработка мобильных приложений.            1       2   
101             Хотел бы повторить тему Java коллекции            1       2   
102    Хочу перепройти вебинар с другим преподователем            1       2   

     is_positive  
0              1  
1              1  
2              1  
3              1  
4              1  
..           ...  
98             1  
99             1  
100            0  
101            0  
102            0  

[103 rows x 9 columns]

In [79]:
val_preds_оb = model_objectt.predict(df_embed_object_test)

In [80]:
from sklearn.metrics import f1_score
f1_val_ob = f1_score(y_test_object, np.array(val_preds_оb).ravel(), average='micro')  
# Или можно использовать 'macro' или 'weighted' в зависимости от вашего выбора
print("F1 Score:", f1_val_ob)

F1 Score: 0.7669902912621359


# relevant

In [81]:
class_weights = compute_class_weight(class_weight = 'balanced', classes = np.unique(relevant),y = relevant)
class_weights

array([1.39300847, 0.77995255])

In [182]:
model_relevant = CatBoostClassifier(iterations=500,
                                    learning_rate=0.001,
                                    depth=5,
                                    eval_metric='F1',
                                    random_seed=0,
                                    class_weights=[3, 1]
                                    # early_stopping_rounds=50
                                    )


In [183]:
y_test_relevant.values

array([1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1])

In [184]:
train_pool = Pool(df_embed_is_relevant, relevant)
val_pool = Pool(df_embed_is_relevant_test, y_test_relevant)


model_relevant.fit(train_pool, eval_set=val_pool, plot=True)

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

0:	learn: 0.7271656	test: 0.2452830	best: 0.2452830 (0)	total: 53.3ms	remaining: 26.6s
1:	learn: 0.7781270	test: 0.2452830	best: 0.2452830 (0)	total: 78.7ms	remaining: 19.6s
2:	learn: 0.8090737	test: 0.0000000	best: 0.2452830 (0)	total: 99ms	remaining: 16.4s
3:	learn: 0.8173804	test: 0.3140496	best: 0.3140496 (3)	total: 121ms	remaining: 15s
4:	learn: 0.8432364	test: 0.1495327	best: 0.3140496 (3)	total: 144ms	remaining: 14.2s
5:	learn: 0.8490566	test: 0.0606061	best: 0.3140496 (3)	total: 165ms	remaining: 13.6s
6:	learn: 0.8677116	test: 0.0000000	best: 0.3140496 (3)	total: 185ms	remaining: 13s
7:	learn: 0.8723810	test: 0.0961538	best: 0.3140496 (3)	total: 209ms	remaining: 12.9s
8:	learn: 0.8768844	test: 0.0606061	best: 0.3140496 (3)	total: 228ms	remaining: 12.4s
9:	learn: 0.8780796	test: 0.0606061	best: 0.3140496 (3)	total: 248ms	remaining: 12.2s
10:	learn: 0.8747640	test: 0.0000000	best: 0.3140496 (3)	total: 268ms	remaining: 11.9s
11:	learn: 0.8846881	test: 0.0434783	best: 0.3140496 (3)

In [188]:


y_test_relevant.values

array([1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1])

In [189]:
np.array(val_preds_rel).ravel()

array([0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1])

In [185]:
val_preds_rel = model_relevant.predict(df_embed_is_relevant_test)

In [186]:
from sklearn.metrics import f1_score
f1_val_rel = f1_score(y_test_relevant, np.array(val_preds_rel).ravel(), average='macro')
print("F1 Score:", f1_val_rel)

F1 Score: 0.4122282608695652


In [123]:
y_test_relevant.values

array([1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1])

In [124]:
val_preds_rel

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [102]:
predictions_rel = model_relevant.predict(df_embed_is_relevant_test)

# Создание датафрейма с одной колонкой "object"
relevant_df_pred = pd.DataFrame({'is_relevant': predictions_rel})

In [103]:
relevant_df_pred

is_relevant
0              1
1              1
2              1
3              1
4              1
..           ...
98             1
99             1
100            1
101            1
102            1

[103 rows x 1 columns]

# positive

In [105]:
class_weights = compute_class_weight(class_weight = 'balanced', classes = np.unique(positive),y = positive)
class_weights

array([1.25957854, 0.82912989])

In [106]:
model_positive = CatBoostClassifier(iterations=500,
                   learning_rate=0.01,
                   depth=4,
                   random_seed=0,
                    class_weights=class_weights)

In [107]:
model_positive.fit(df_embed_is_positive, positive, use_best_model=True)

You should provide test set for use best model. use_best_model parameter has been switched to false value.


0:	learn: 0.6867968	total: 27.5ms	remaining: 13.7s
1:	learn: 0.6798758	total: 47.8ms	remaining: 11.9s
2:	learn: 0.6726790	total: 62.9ms	remaining: 10.4s
3:	learn: 0.6670069	total: 77.1ms	remaining: 9.56s
4:	learn: 0.6616174	total: 89.9ms	remaining: 8.9s
5:	learn: 0.6553290	total: 102ms	remaining: 8.4s
6:	learn: 0.6491436	total: 114ms	remaining: 8.06s
7:	learn: 0.6437096	total: 126ms	remaining: 7.76s
8:	learn: 0.6371966	total: 138ms	remaining: 7.53s
9:	learn: 0.6323209	total: 150ms	remaining: 7.37s
10:	learn: 0.6265628	total: 166ms	remaining: 7.39s
11:	learn: 0.6206830	total: 181ms	remaining: 7.36s
12:	learn: 0.6145867	total: 197ms	remaining: 7.38s
13:	learn: 0.6094507	total: 210ms	remaining: 7.3s
14:	learn: 0.6039428	total: 229ms	remaining: 7.39s
15:	learn: 0.5990187	total: 247ms	remaining: 7.46s
16:	learn: 0.5943657	total: 262ms	remaining: 7.44s
17:	learn: 0.5891648	total: 276ms	remaining: 7.38s
18:	learn: 0.5843071	total: 288ms	remaining: 7.29s
19:	learn: 0.5793779	total: 302ms	remai

In [195]:
from sklearn.metrics import precision_score, recall_score, f1_score

In [196]:
val_preds_pos = model_positive.predict(df_embed_is_positive_test)

In [197]:
from sklearn.metrics import f1_score
f1_val_pos = f1_score(y_test_positive, np.array(val_preds_pos).ravel(), average='macro')
print("F1 Score:", f1_val_pos)

F1 Score: 0.8843995510662177


СУПЕР ВАЖНАЯ ФУНКЦИЯ 


In [198]:
def evaluate_model(y_true, y_pred):
    precision = precision_score(y_true, y_pred, average='macro')
    recall = recall_score(y_true, y_pred, average='macro')
    f1 = f1_score(y_true, y_pred, average='macro')
    return precision, recall, f1


In [199]:
evaluate_model(y_test_positive, val_preds_pos)

(0.8623417721518987, 0.9138554216867469, 0.8843995510662177)

In [200]:
evaluate_model(y_test_relevant, val_preds_rel)

(0.45173160173160176, 0.4047008547008547, 0.4122282608695652)

In [201]:
evaluate_model(y_test_object, val_preds_оb)

(0.7856118056978888, 0.7733500417710945, 0.7692637305313362)

In [ ]:
predictions_pos = model_positive.predict(X_test_positive)

# Создание датафрейма с одной колонкой "object"
positive_df_pred = pd.DataFrame({'is_relevant': predictions_pos})

In [102]:
np.array(val_preds_pos).ravel()

array([1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1.,
       1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 0., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0.,
       1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1.,
       0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1.,
       1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       1., 0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1.])